// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5QyVrRQofxyXjCE8yvy55cxTgVpjLHpw',
    appId: '1:609104514525:web:d2061125e368e34b39ba34',
    messagingSenderId: '609104514525',
    projectId: 'toktik-app',
    authDomain: 'toktik-app.firebaseapp.com',
    storageBucket: 'toktik-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlU0hEYl7Y5fA4xD7C4PIsi9Bk_5qX0fs',
    appId: '1:609104514525:android:637fbe7ab96701c939ba34',
    messagingSenderId: '609104514525',
    projectId: 'toktik-app',
    storageBucket: 'toktik-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgW0KuKO_zmxGSC0ccPGYtle5nAEQZ1HA',
    appId: '1:609104514525:ios:18b3676aeef81ddb39ba34',
    messagingSenderId: '609104514525',
    projectId: 'toktik-app',
    storageBucket: 'toktik-app.appspot.com',
    iosClientId: '609104514525-tvkodh84vd36mgg7kk0d56t2d82qft8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.toktik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgW0KuKO_zmxGSC0ccPGYtle5nAEQZ1HA',
    appId: '1:609104514525:ios:18b3676aeef81ddb39ba34',
    messagingSenderId: '609104514525',
    projectId: 'toktik-app',
    storageBucket: 'toktik-app.appspot.com',
    iosClientId: '609104514525-tvkodh84vd36mgg7kk0d56t2d82qft8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.toktik',
  );
}
